const header = document.querySelector('header');
const footer = document.querySelector('footer');
const main = document.querySelector('main');
const a = document.querySelector('a');
const div = document.querySelector('div');
const span = document.querySelector('span');
const p = document.querySelector('p');
const h1 = document.querySelector('h1');
const h2 = document.querySelector('h2');
const h3 = document.querySelector('h3');
const h4 = document.querySelector('h4');
const h5 = document.querySelector('h5');
const h6 = document.querySelector('h6');
const img = document.querySelector('img');
const body = document.querySelector('body');
const table = document.querySelector('table');
const tr = document.querySelector('tr');
const td = document.querySelector('td');
const th = document.querySelector('th');
const ul = document.querySelector('ul');
const li = document.querySelector('li');
const nav = document.querySelector('nav');

export { header, footer, main, a, div, span, p, h1, h2, h3, h4, h5, h6, img, body, table, tr, td, th, ul, li, nav };
